[package]
name = "with-tailwind"
version = "0.0.1"
edition = "2021"

[[bin]]
name = "tuono"
path = ".tuono/main.rs"

[dependencies]
reqwest = "0.12.12"
serde = { version = "1.0.202", features = ["derive"] }
tuono_lib = "0.17.5"
