packages:
- 'apps/*'
- '!**/test/**'

catalog:
  '@biomejs/biome': ^1.9.4
  consola: ^3.2.3
  nitropack: ^2.9.7
  npm-check-updates: ^17.1.9
  pathe: ^1.1.2
  std-env: ^3.7.0
  typescript: ^5.6.3
  wrangler: ^3.84.1
